### ISSUE TITLE
[Bug]: Other players cant see or shoot the arrows

### ISSUE THREAD

**Issue by Bareld** [Digitalroot-Valheim/Atokal-AtosArrowsJVL#13]
### How are you playing the game?

Multiplayer - My Client Hosts Server

### What happened?

hello o7.
I can use these arrows fine as host...but others connected to my server cant use the arrows...they all have the exact same mod/version of atosarrows jvl.
They can craft, select and fire the arrow but nothing happens when they fire them.

this line shows up in console when they try to shoot these arrows

[Info   : Unity Log] 02/12/2022 00:33:00: Destroyed invalid predab ZDO:214875948:2973

i hope you know what this means o7

### Relevant log output

```shell
[Info   : Unity Log] 02/12/2022 00:33:00: Destroyed invalid predab ZDO:214875948:2973
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Digitalroot** [comment]
If they play solo does the mod work?

**Comment by Bareld** [comment]
> 

yes, it works perfectly when they play on their own map/ singleplayer

**Comment by Digitalroot** [comment]
So far, in my testing of MP, it is working. This leads me to believe there is a mod conflict I am unaware of. 

Please install this mod. https://www.nexusmods.com/valheim/mods/1302

Please edit your "**BepInEx.cfg**" update the `[Logging.Disk]` section to look like this. 

```
[Logging.Disk]

## Include unity log messages in log file output.
# Setting type: Boolean
# Default value: false
WriteUnityLog = true

## Appends to the log file instead of overwriting, on game startup.
# Setting type: Boolean
# Default value: false
AppendLog = false

## Enables writing log messages to disk.
# Setting type: Boolean
# Default value: true
Enabled = true

## Which log leves are saved to the disk log output.
# Setting type: LogLevel
# Default value: Fatal, Error, Warning, Message, Info
# Acceptable values: None, Fatal, Error, Warning, Message, Info, Debug, All
# Multiple values can be set at the same time by separating them with , (e.g. Debug, Warning)
LogLevels = All
```

Please do this on both the client hosting the game and the clients connecting to the host. 

1. Reproduce the error. 
2. Exit the game. 
3. Upload "**LogOutput.log**" from the host client as "**LogOutput.Host.log**"
4. Upload "**LogOutput.log**" from the connecting client as "**LogOutput.Client.log**"

**Comment by Bareld** [comment]
[LogOutput.Host.log](https://github.com/Digitalroot-Valheim/Atokal-AtosArrowsJVL/files/8082122/LogOutput.Host.log)
[LogOutput.Client.log](https://github.com/Digitalroot-Valheim/Atokal-AtosArrowsJVL/files/8082125/LogOutput.Client.log)

these are the log files i hope its good enough o7

**Comment by Digitalroot** [comment]
Dunno why this isn't updated.
[LogOutput.Host.log](https://github.com/Digitalroot-Valheim/Atokal-AtosArrowsJVL/files/8092843/LogOutput.Host.log)
[LogOutput.Client.log](https://github.com/Digitalroot-Valheim/Atokal-AtosArrowsJVL/files/8092845/LogOutput.Client.log)

**Comment by Digitalroot** [comment]
Just me talking to myself. I had the logs in another view so I just added them. Thanks for the newer logs
