### ISSUE TITLE
[Bug]: Item Tooltip not showing

### ISSUE THREAD

**Issue by NothingREM** [Digitalroot-Valheim/Atokal-AtosArrowsJVL#14]
### How are you playing the game?

Multiplayer - Dedicated Server

### What happened?

Just noticed the tooltip description for the Blunted Arrow is not showing.

### Log File

![image](https://user-images.githubusercontent.com/59773819/167313799-cf7697ec-c375-496b-b6bf-7b97526b3272.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DrGibaud** [comment]
Same problem with me for every tipe of arrow included in this mod.
Name of the arrow ("blunted arrow" for example in the craftable list on the left tab and name plus tooltip description on the right tab are missing.

**Comment by Digitalroot** [comment]
This happens when the translation file is in the incorrect place.

**Comment by DrGibaud** [comment]
Thanks for the answer.
How can i solve this problem?
I mean i have installed the addon with thunderstorm client and hope it has placed the folder in the correct place.
How can i verify it?

**Comment by GinFizzz** [comment]
Can confirm that this occurs when installing the mod through r2modman, as well as thunderstorm client.

**Comment by GinFizzz** [comment]
Looks like r2ModMan doesn't like to follow down directories.

BoneArrowsJVL has a plugin folder with the Assets folder and dll in it. 
AtosArrows has no plugin folder, and instead has an AtosArrowsJVL folder, which seems to be treated differently by r2ModMan.

**Comment by DrGibaud** [comment]
Thx a lot for the answer again.
Now it works properly.
