### ISSUE TITLE
[Bug]: Are Exploding Fire/Ice Arrows Missing? (Also possible files missing from zip.)

### ISSUE THREAD

**Issue by louhy** [Digitalroot-Valheim/Atokal-AtosArrowsJVL#17]
### How are you playing the game?

Multiplayer - My Client Hosts Server

### What happened?

Things look okay other than those two options missing from the crafting table.

Are assets missing? The repo has additional files that aren't inside the zip from Nexusmods. Also I see "assets/atosarrows/arrows/arrowfireaoe.prefab" in the source but the only folder inside the Assets folder is Translations.

(Also for Linux users using Proton, file and folder case sensitivity matters, and that folder is 'Assets' while that path is 'assets'.) 

### To Reproduce

No steps, just look at the list in the crafting table. Tried creating "Fire Bomb" to see if that'd add the missing arrow option, no good.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Digitalroot** [comment]
![image](https://github.com/Digitalroot-Valheim/Atokal-AtosArrowsJVL/assets/3770289/375f18b6-4f85-4973-9d46-37777154cb38)
This is the correct files. 

The prefabs are embedded in the main dll file. So you don't need them to play the game. 

That path `assets/atosarrows/arrows/arrowfireaoe` is the path inside the dll to load the assets from.

**Comment by louhy** [comment]
Ok, that was just a guess at what might be the issue. 

With that folder with those files installled, I don't see those Exploding Fire/Ice Arrow options anywhere (but I do get all the other stuff), so it seems like something's wrong.

**Comment by louhy** [comment]
Ooh hold a second, maybe they don't show up until you satisfy the workbench conditions. Found this in the code: 

_MinStationLevel = 6_

So probably "not a bug", unless I'm mistaken and it should show up in the list regardless.
