### ISSUE TITLE
[Bug]: Vanilla UI, Better UI Reforged and Auga are all showing Prefab names in Workbench rather than item name.

### ISSUE THREAD

**Issue by General-Ripper** [Digitalroot-Valheim/Atokal-AtosArrowsJVL#20]
### How are you playing the game?

Single Player - No Server

### What happened?

okay so, I am playing valheim in an older version (my valheim version is: (v0.217.31) 
and my mod list: https://pastebin.pl/view/6fd06fb3
I was using Auga and in this version it's stable AF. so I thought anyhow it has issues it might be mod conflict so I changed to Better UI Reforged (forever maintained version), still in the workbench it shows Prefab names in rather than item names. (i.e instead of lightening arrows, I could only prefab names which is ugly as hell) so I got rid of Better UI too, and tried with game vanilla UI, still the same thing. what could be the cause? I have loads of mods, none of them behave like this. any suggestions? 

### To Reproduce
Dunno what to do. it's just ugly looking otherwise it works like charm.

### Screenshots
do you need this? sure. I'll edit and add if you want. 

_No response_

### Relevant log output

```shell
%% I uploaded BepInEx Logs. Nothing caught my eyes tho.
```

### Log File

[LogOutput.log](https://github.com/Digitalroot-Valheim/Atokal-AtosArrowsJVL/files/14706702/LogOutput.log)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Digitalroot** [comment]
I think you are missing the translation file. https://github.com/Digitalroot-Valheim/Atokal-AtosArrowsJVL/tree/main/src/AtosArrowsJVL/Assets/Translations
