### ISSUE TITLE
Missing Translations

### ISSUE THREAD

**Issue by Digitalroot** [Digitalroot-Valheim/Atokal-AtosArrowsJVL#4]
**Describe the bug**
In some places, the name of the arrows was not translated, but the inventory was translated

**Screenshots**

![image](https://user-images.githubusercontent.com/3770289/126889955-4d6bf639-f637-47b6-9461-90cba849fd65.png)

![image](https://user-images.githubusercontent.com/3770289/126889962-22b8ce11-866c-4f58-b063-c1cdfa9fd7e8.png)

**Comment by Digitalroot** [comment]
Looks like the follow is missing for English too

- IceBomb
- FireBomb
- StoneArrow
- CoreArrow
- BoneArror
- HeavyObsidianArrow
- HeavyNeedleArrow
- BigFireArrow aka Obsidian Fire Arrow
- FireAoeArrow aka Exploding Fire Arrow
- HeavyIceArrow
- HeavyPoisonArrow
- PoisonAoeArrow
- Xbow

**Comment by Biatlonist** [comment]
{"item_atoarrow_stone", "Стрела Каменная"},
 {"item_atoarrow_stone_description", "Грубая стрела с затупленным каменным наконечником. Хорош для того, чтобы разностить в щепки что-то на расстоянии."},
 {"item_atoarrow_core", "Стрела Затупленная бронзовая"},
 {"item_atoarrow_core_description", "Стрела с тупым бронзовым наконечником. Отлично подходит для удара по черепу на расстоянии."},
 {"item_atoarrow_heavy_core", "Тяжелая Тупая стрела"},
 {"item_atoarrow_heavy_core_description", "Крепкая и хорошо сделанная стрела. Гораздо труднее сделать, но наносит гораздо больший урон."},
 {"item_atoarrow_bone", "Стрела Костяная"},
 {"item_atoarrow_bone_description", "Стрела, сделанная из нескольких костяных фрагментов. Эта уникальная стрела режет и разрывает плоть ваших врагов."},
 {"item_atoarrow_heavy_bone", "Тяжелая Костяная стрела"},
 {"item_atoarrow_heavy_bone_description", "Стрела, сделанная из нескольких костяных фрагментов. Эта уникальная стрела режет и разрывает плоть ваших врагов."},
 {"item_atoarrow_heavy_flint", "Тяжелая Кремневая стрела"},
 {"item_atoarrow_heavy_flint_description", "Крепкая и хорошо сделанная стрела. Гораздо труднее сделать, но наносит гораздо больший урон."},
 {"item_arrow_heavyobsidian", "Тяжелая обсидиановая стрела"},
 {"item_arrow_obsidian_heavy_description", "Тяжелая стрела, сделанная с твердым обсидиановым наконечником".},
 {"item_arrow_heavyneedle", "Тяжелая игольчатая стрела"},
 {"item_arrow_heavyneedle_description", "Более тяжелая и тяжелая игольная стрела".},
 {"item_arrow_obsidianfire", "Стрела Огненная из Обсидиана"},
 {"item_arrow_obsidianfire_description", "Мощная стрела, которая воспламенит ваших врагов."},
 {"item_arrow_heavyfire", "Тяжелая огненная стрела"},
 {"item_arrow_heavyfire_description", "Крепкая и хорошо сделанная стрела. Гораздо труднее сделать, но наносит гораздо больший урон."},
 {"item_atoarrow_bigfire", "Стрела Огненная взрывающаяся"},
 {"item_atoarrow_bigfire_description", "Стрела, до краев заряженная взрывчаткой. Эта редкая стрела отлично подходит для того, чтобы поджечь все вокруг!"},
 {"item_arrow_heavy_frost", "Тяжелая ледяная стрела"},
 {"item_arrow_frost_heav_description", "Крепкая и хорошо сделанная стрела. Гораздо труднее сделать, но наносит гораздо больший урон."},
 {"item_atoarrow_bigice", "Стрела Ледяная взрывающаяся"},
 {"item_atoarrow_bigice_description", "Стрела, до краев наполненная всевозможными магическими холодными предметами, найденными в горах. Эта редкая стрела отлично подходит для замораживания нескольких врагов!"},
 {"item_arrow_heavy_poison", "Тяжелая ядовитая стрела"},
 {"item_arrow_poison_heavy_description", "Крепкая и хорошо сделанная стрела. Гораздо труднее сделать, но наносит гораздо больший урон."},
 {"item_atoarrow_aoepoison", "Стрела Ядовитая взрывающаяся"},
 {"item_atoarrow_aoepoison_description", "Стрела, до краев наполненная ядом и сочащаяся. Эта редкая стрела отлично подходит для отравления большой группы врагов."},
 {"item_ato_firebomb", "Бомба Огненная"},
 {"item_ato_firebomb_description", "Изобретение от гнома Хьюго".},
 {"item_ato_icebomb", "Бомба Леденая"},
 {"item_ato_icebomb_description", "Изобретение от гнома Хьюго".},
 {"item_xbow", "Арбалет"},
 {"item_xbow_description", "Болт для арбалета"},

**Comment by Biatlonist** [comment]
new translation

**Comment by Biatlonist** [comment]
IceBomb - Бомба Леденая
 FireBomb - Бомба Огненная
StoneArrow - Стрела Каменная
CoreArrow - Стрела Затупленная бронзовая
BoneArror - Стрела Костяная
HeavyObsidianArrow - Тяжелая обсидиановая стрела
HeavyNeedleArrow -Тяжелая игольчатая стрела
 BigFireArrow aka Obsidian Fire Arrow - Стрела Огненная из Обсидиана
 FireAoeArrow aka Exploding Fire Arrow - Стрела Огненная взрывающаяся
 HeavyIceArrow - Стрела Ледяная взрывающаяся
 HeavyPoisonArrow - Тяжелая ядовитая стрела
 PoisonAoeArrow - Стрела Ядовитая взрывающаяся
 Xbow - Арбалет

**Comment by Digitalroot** [comment]
> new translation

Which language is that?
