### ISSUE TITLE
[Bug]: When using mod manager the user has to rename the folder manually

### ISSUE THREAD

**Issue by werner-mayer** [Digitalroot-Valheim/Atokal-AtosArrowsJVL#6]
### How are you playing the game?

Multiplayer - Dedicated Server

### What happened?

i installed that via modmanager, i needed to rename the folder to "AtosArrows" to make it work 

[Info   :AtosArrowsJVL.AtosArrows] AtosArrows.Awake()
[Error  :AtosArrowsJVL.AtosArrows] Unable to find asset file 'atoarrows', please make sure 'atoarrows' and 'AtosArrowsJVL.dll' are in C:\Users\xx\AppData\Roaming\Thunderstore Mod Manager\DataFolder\Valheim\profiles\Default\BepInEx\plugins\AtosArrowsJVL

### To Reproduce

1. Install via modManager
2. Open Valheim
3. See the logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Digitalroot** [comment]
Updated to v0.7.5
Fixed in #7
