### ISSUE TITLE
[Bug]: Didn't load when installed with mod manager

### ISSUE THREAD

**Issue by matthewwyndham** [Digitalroot-Valheim/Atokal-AtosArrowsJVL#8]
### How are you playing the game?

Single Player - No Server

### What happened?

I installed the mod through r2modman and it automatically installed it in the plugins with the folder name "OdinPlus-AtosArrowsJVL".

The mod wouldn't load properly and I kept getting an error message saying that it could not find `.../Valheim/profiles/Default/BepInEx/plugins/AtosArrowsJVL` so I copied all the files from "OdinPlus-AtosArrowsJVL" to "AtosArrowsJVL" and then it was able to load properly.

I don't know where in the process the name of the plugins folder gets decided, but it seems like it is broken somewhere. I don't know if this issue still occurs when manually installing, and I also don't know if it was just a fluke.

### To Reproduce

1. Install through r2modman
2. Launch the game
3. Check the debugger window for an error trying to load from the wrong folder name.

### Relevant log output

```shell
[Error  :AtosArrowsJVL.AtosArrows] Unable to find asset file 'atoarrows', please make sure 'atoarrows' and 'AtosArrowsJVL.dll' are in C:\Users\admin\AppData\Roaming\r2modmanPlus-local\Valheim\profiles\Default\BepInEx\plugins\AtosArrowsJVL
[Error  :AtosArrowsJVL.AtosArrows] AtosArrowsJVL is not loaded.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Digitalroot** [comment]
There is an update on Nexus that resolves this. I think I forgot to update TS with the new version. 

Thank you for reporting this. I'll update TS.

**Comment by Digitalroot** [comment]
New version uploaded to TS. LMK if it does not work.
