### ISSUE TITLE
Using bow says I have no arrows

### ISSUE THREAD

**Issue by murmeel** [Digitalroot-Valheim/Atokal-AtosArrowsJVL#9]
### How are you playing the game?

Single Player - No Server

### What happened?

I equipped my Crude Bow and had a stack of Stone Arrows in my inventory (and selected). 
But when I try to shoot it says I have no arrows.

### To Reproduce

1. Start solo game locally
2. Get a crude bow
3. Get Stone Arrows (or possibly other arrows belonging to this mod) and equip them
4. Try to shoot an arrow

### Screenshots

![ArrowBug](https://user-images.githubusercontent.com/5817862/134251920-778775fe-db6a-4c6a-95d3-1604d767436f.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Digitalroot** [comment]
This is 100% an issue with the HnH update. I have been focused on fixing my other mods atm. I do know this is fixable. I plan to get to it as soon as I am done fixing my Bounties mod.

**Comment by Digitalroot** [comment]
This is fixed in the new release.
